config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :enrollments
  devise_for :users
  resources :users
  resources :courses do
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  get 'home/index', as: 'home'
  get 'static/index'
  # root 'courses#index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
  validates :course_id, :user_id, presence: true
  validates :course_id, :uniqueness => { :scope => :user_id }
  validates :user_id, :uniqueness => { :scope => :course_id }
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]
  before_action :set_course, only: [:new, :create]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
    authorize @enrollments
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = current_user.buy_course(@course)
    redirect_to course_path(@course), notice: 'you are enrolled'
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:course_id, :user_id)
    end

  def set_course
    @course = Course.friendly.find(params[:course_id])
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :course
    = f.association :user

  .form-actions
    = f.button :submit

app/views/enrollments/edit.html.haml
%h1 Editing enrollment

= render 'form'

= link_to 'Show', @enrollment
\|
= link_to 'Back', enrollments_path

app/views/enrollments/index.html.haml
%h1 Listing enrollments

%table.table
  %thead
    %tr
      %th Course
      %th User
      %th Price
      %th
      %th
      %th

  %tbody
    - @enrollments.each do |enrollment|
      %tr
        %td= enrollment.course
        %td= enrollment.user
        %td= number_to_currency(enrollment.price)
        %td= link_to 'Show', enrollment
        %td= link_to 'Edit', edit_enrollment_path(enrollment)
        %td= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Enrollment', new_enrollment_path

app/views/enrollments/new.html.haml
.card
  .card-header
    New enrollment
  .card-body
    = form_tag course_enrollments_path(@course) do
      = submit_tag 'Buy Now!'
  .card-footer
= link_to 'Back', enrollments_path

app/views/enrollments/show.html.haml
%p#notice= notice

%p
  %b Course:
  = @enrollment.course
%p
  %b User:
  = @enrollment.user
%p
  %b Price:
  = @enrollment.price

= link_to 'Edit', edit_enrollment_path(@enrollment)
\|
= link_to 'Back', enrollments_path