config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :enrollments
  devise_for :users
  resources :users
  resources :courses do
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  get 'home/index', as: 'home'
  get 'static/index'
  # root 'courses#index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert" }
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    = link_to 'CMS', root_path, class: 'navbar-brand'
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          = link_to 'Home', home_path, class: 'nav-link active'
        %li.nav-item
          = link_to 'Courses', courses_path, class: 'nav-link'
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            Categories
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            - categories.each do |category|
              %li
                = link_to category.name, courses_path(category: category.id), class: 'dropdown-item'
      -#%form.d-flex
      -#  %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      -#  %button.btn.btn-outline-success{:type => "submit"} Search
      %div.navbar-nav
        - if current_user
          = link_to "#{is_admin? ? 'Admin' : 'Student'} Account Settings", edit_user_registration_path, class: 'nav-link'
          = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          = link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
          = link_to 'Login', new_user_session_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = content_for?(:title) ? yield(:title) : CourseManagementSystem
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    = render 'layouts/messages'
    .container
      = yield